name: push

on:
  push:
    branches:
      - gh-pages


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: ssh
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        command_timeout: 10000m
        script: |
          ps
          ps -efw | grep "[n]pm run dev" | awk '{print $2}' | xargs kill
          cd ~/launch.github.io
          git pull origin gh-pages

          npm install next nextjs-progressbar next-qrcode

          ls -alF
          npm run dev
