name: push

on:
  push:
    branches:
      - gh-pages


jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: ssh
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd ~/launch.github.io
          git pull origin gh-pages

          npm install next
          
          ls -alF
          cat package.json
          npm run dev
