name: Deploy to Github Pages

on:
  push:
    branches:
      - gh-pages

  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Build
        run: |
          npm install axios rot47 @nivo nextjs-progressbar
          git config --global user.name "twepdev"
          git config --global user.email "twepv2dev@gmail.com"
          git add .
          git commit -m 'changed files'
          git push origin gh-pages

          npm install next
          npm run build
          npm run export

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./out