name: push

on:
  push:
    branches:
      - gh-pages


jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: ssh
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          rm -rf launch.github.io
          git clone -b gh-pages TwepDev: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@github.com/TwepDev/launch.github.io.git
          cd ~/launch.github.io
          git pull origin gh-pages
          ls -alF
          cat package.json
          npm run dev
