name: push

on:
  push:
    branches:
      - gh-pages


jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: ssh
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          git clone -b gh-pages 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@github.com/TwepDev/launch.github.io.git
          ls